name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app/sasblog
            git pull origin main
            /home/ubuntu/.nvm/versions/node/v24.14.1/bin/pnpm install --frozen-lockfile
            /home/ubuntu/.nvm/versions/node/v24.14.1/bin/pm2 restart sasblog
